// <auto-generated />
namespace TorneioFutebol.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddTimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTimes));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101742164_AddTimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
